# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v?[0-9]+\.[0-9]+\.[0-9]+'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Heroku Docker Container Deploy
        # You may pin to the exact commit or the version.
        # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          # Email Linked to your Heroku Account
          email: truemosspiglets@gmail.com
          # Your Heroku API Key
          api_key: ${{secrets.HEROKU_KEY}}
          # Your Heroku App Name
          app_name: WizardWorldApi
          # Dokerfile path
          dockerfile_path: WizardWorldApi/Dockerfile
 
