name: Deploy

on:
  push:
    # Trigger workflow on tags like v1.2.3
    tags:
      - 'v?[0-9]+\.[0-9]+\.[0-9]+'
  # Allow manual workflow run from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - uses: actions/checkout@v3

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh 

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_KEY }}
          heroku_app_name: wizard-world-api
          heroku_email: truemosspiglets@gmail.com
          usedocker: true
          appdir: WizardWorldApi
