name: .NET

on:
  pull_request:
    branches: [ develop ]
    
defaults:
      run:
        working-directory: ./WizardWorldApi

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal WizardWorldApi.Tests.Unit/WizardWorldApi.Tests.Unit.csproj
