services:
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'

    ports:
      - "7165:5432"

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: MossPiglets # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: WizardWorld # The PostgreSQL default database (automatically created at first launch)

